export const departmentsOptions = [
    "IT & Software Development",
    "Sales",
    "Human Resources",
    "Accounting & Finance",
    "Legal Services",
    "Call Center & Customer Service",
    "Business Development",
    "Quality Assurance",
    "Procurement & Purchasing",
    "Logistics & Supply Chain",
    "Event Planning",
    "Customer Relations",
    "Digital Marketing",
    "Science & Research",
    "Real Estate & Property Management",
    "Engineering",
    "Manufacturing",
    "Design & Creative Arts",
    "Warehouse Management",
    "Administrative & Office Support",
    "Operations Management",
    "Textile & Garment",
    "Education & Training",
    "Non-Profit & NGO",
    "Agriculture & Farming",
    "Architecture & Construction",
    "Automotive Industry",
    "Banking & Financial Services",
    "Beauty & Wellness",
    "Construction & Building",
    "Consulting",
    "Data Entry",
    "Event Management",
    "Facilities Management",
    "Fashion & Apparel",
    "Food & Beverage",
    "Healthcare & Pharmaceuticals",
    "Hospitality & Tourism",
    "Marking & Advertising",
    "Medical Services",
    "Media & Entertainment",
    "Office Management",
    "Petroleum & Energy",
    "Pharmaceuticals",
    "Public Administration",
    "Research & Development",
    "Security & Protection",
    "Social Services",
    "Sports & Recreation",
    "Telecommunication",
    "Tourism & Hospitality",
    "Transportation & Logistics",
    "Urban Planning",
    "Veterinary Services",
    "Web Development",
    "Aviation",
    "Biotechnology",
    "chemical Engineering",
    "Civil Engineering",
    "Computer Hardware",
    "Corporate Training",
    "Digital Design",
    "E-commerce",
    "Facilities Maintenance",
    "Financial Planning",
    "Food Science",
    "Graphic Design",
    "Health Informatics",
    "Humanitarian Aid",
    "Industrial Design",
    "Interior Design",
    "Journalism",
    "Laboratory Technician",
    "Legal Assistant",
    "Mechanical Engineering",
    "Medical Assistant",
    "Nursing",
    "Occupational Therapy",
    "Petroleum Engineering",
    "Physical Therapy",
    "Public Health",
    "Software Testing",
    "Systems Analysis",
    "Architecture & Engineering",
    "Banking & Insurance",
    "Design & Creative",
].map(option => ({ label: option, value: option }));