export const industries = [
    "Education",
    "Engineering",
    "Food Service",
    "Information Technology",
    "Other Services",
    "Cosmetics",
    "Pharmaceuticals",
    "Chemicals",
    "Stationery, office equipment and interiors",
    "Apparel, clothing, sundries and leather goods",
    "Printing",
    "Automobiles",
    "Transport equipment",
    "Machinery",
    "Plan & engineering",
    "General electrical (electrical and electronic equipment)",
    "Medical equipment",
    "Precision equipment",
    "Heavy electric machinery and industrial electrical equipment",
    "Computer, communication and offices equipment",
    "Semiconductors, electronic components and others",
    "Home appliances and audio equipment",
    "Gaming and amusement equipment",
    "Housing",
    "Construction",
    "Equipment and installation work",
    "Building materials and exteriors",
    "Textiles",
    "Paper and pulp",
    "Glass & ceramics",
    "Tyres and rubber products",
    "Petroleum and coal",
    "Metal products",
    "Non-ferrous metals",
    "Steel, mining and cement",
    "Agriculture, agriculture and forestry",
    "Fisheries",
    "Other manufacturers",
    "All services and infrastructure",
    "Travel",
    "Hotels",
    "Leisure, amusement and pachinko",
    "Arts and entertainment",
    "Sports, fitness and health facilities",
    "Real estate",
    "Public/government offices",
    "Aviation & airports",
    "Railways",
    "Shipping",
    "Land transport",
    "Taxis, buses and tourist buses",
    "Warehousing",
    "Power and electricity",
    "Energy",
    "Gas and water",
    "Restaurant",
    "Human resource services",
    "Consultants/specialist consultants",
    "Construction consultants",
    "Think tanks",
    "Medical related/medical institutions",
    "Welfare and nursing care",
    "Bridal, weddings and funerals",
    "Esthetics, hairdressing and beauty",
    "Associations",
    "Architectural design",
    "Security, safety, maintenance, cleaning",
    "Mechanical design",
    "All trading companies",
    "General trading, company",
    "Game software",
    "Information processing",
    "Other department stores, speciality shops, distribution and retail",
    "Spectacles, contact lenses and medical equipment",
    "Home appliances, office equipment, cameras",
    "Automobiles and transport equipment",
    "Sporting goods",
    "Drugstores, pharmaceuticals, cosmetics and dispensing pharmacies",
    "Fashion, clothing and textiles",
    "Music, books and interior design",
    "Consumer cooperatives",
    "Home improvement centers",
    "Supermarkets/stores",
    "Department stores/department stores/commercial complexes",
    "Telecommunications",
    "Newspapers",
    "Broadcasting, television and radio",
    "Publishing/magazines",
    "Advertising",
    "Other banking, securities, insurance and finance",
    "Consumer finance",
    "Leasing and rental",
    "Credit and consumer credit",
    "Securities",
    "Non-life insurance",
    "Life insurance",
    "Government-affiliated/group financial institutions",
    "Foreign-affiliated financial institutions",
    "Credit unions, labour banks, mutual aid",
    "Regional banks",
    "City banks/trust banks",
    "Other trading companies",
    "Petroleum products",
    "Paper",
    "Building materials and exteriors",
    "Metals",
    "Electrical, electronics and semiconductors",
    "Office equipment",
    "IIG",
    "ITG",
    "Health care",
    "Consultant",
    "NGO",
    "Paint",
    "Import/export furniture",
    "Internet",
    "Facility management",
    "Cargo and freight",
    "Software development",
    "Matrimony",
    "3D animation",
    "VFX",
    "Film",
    "Advertising",
    "Supply chain & logistics",
    "E-commerce",
];