export const positions = [
    "CEO",
    "CFO",
    "CMO",
    "Graphic",
    "Web",
    "CG",
    "Fashion",
    "Game",
    "UI/UX",
    "Interior",
    "Illustrator",
    "CTO",
    "Representative",
    "Staff Recruiter",
    "Compensation Analyst",
    "HR Analyst",
    "HR Administrator",
    "Administrator",
    "Clerk",
    "Receptionist",
    "Auditor",
    "Bookkeeper / Accounting Clerk / Staff Accountant",
    "Financial Analyst",
    "Equity Analyst",
    "Sales Assistant / Sales Support Specialist",
    "Territory Manager / Regional Manager",
    "Sales Representative / Associate / Executive",
    "Account Executive",
    "Sales Associate / Sales Staff",
    "Digital marketing (e-mail, content marketing)",
    "Web marketing (web advertising, affiliate advertising, SEO)",
    "CRM",
    "Marketing Director (planning, planning)",
    "Content Marketer (owned media, paid media, earned media)",
    "SNS marketer",
    "Influencer Marketing",
    "Teachers and tutors",
    "Accountants and tax accountants",
    "Doctor / Dentist",
    "Nurse / Nurses",
    "Caregivers",
    "Dental Hygienist",
    "Pharmacists",
    "Pilot",
    "Business Consultant/Analyst",
    "Financial Dealer",
    "Fund Manager/Loan Officer",
    "Child Care Worker (Mother / Father) / Kindergarten Teacher",
    "University staff",
    "Interpreter/translator",
    "Nutritionist",
    "National public employee",
    "Local government employee",
    "Lawyer",
    "Securities analyst",
    "Psychological counselor",
    "Occupational and physical therapists",
    "Clinical laboratory technician",
    "Judicial scriveners and administrative scriveners",
    "Beautician",
    "Wedding planner",
    "Strategy & Development manager",
    "Lead Generator & Telemarketer",
    "Route Sales",
    "Corporate Sales",
    "Individual Sales",
    "Inside sales",
    "Tele-appointment sales",
    "Engineer",
    "Software Developer",
    "Internship",
    "Executive",
    "Manager",
    "Officer",
    "Analyst",
    "News Reporter",
    "Medical Officer",
    "Assistant Manager",
    "General Manager",
    "Instructor",
    "Video Editor",
    "Supply Chain Executive",
    "Data Analyst",
    "Tech Lead",
    "Project Manager",
    "Merchandiser",
    "Associate Director",
    "HR Compliance",
    "Director",
    "Associate",
    "Deputy Manager",
    "Head of Procurement",
    "Supervisor",
    "CA",
    "ACCA",
    "Store In-Charge",
    "Head",
    "Value Chain Facilitator",
    "Others",
    "Management Trainee",
    "Computer Operator",
    "Digital Marketing & Content Creation/Designer",
    "Lab Assistant",
    "Electrician",
    "Inspector",
    "Consultant",
    "Specialist",
    "Assistant",
    "Architect",
    "Technician",
    "Cleaner",
    "Chef",
    "Medical Transcriptionist",
    "Delivery Man",
    "Delivery Executive",
    "Cyclist",
    "Rider",
    "Company Biker",
    "Own Biker",
    "Counsellor",
    "Senior Counsellor",
];