export const options = [
    { value: "University of Dhaka", label: "University of Dhaka" },
    { value: "University of Rajshahi", label: "University of Rajshahi" },
    { value: "Bangladesh Agricultural University", label: "Bangladesh Agricultural University" },
    { value: "Bangladesh University of Engineering & Technology", label: "Bangladesh University of Engineering & Technology" },
    { value: "University of Chittagong", label: "University of Chittagong" },
    { value: "Jahangirnagar University", label: "Jahangirnagar University" },
    { value: "Islamic University, Bangladesh", label: "Islamic University, Bangladesh" },
    { value: "Shahjalal University of Science and Technology", label: "Shahjalal University of Science and Technology" },
    { value: "Khulna University", label: "Khulna University" },
    { value: "Bangabandhu Sheikh Mujib Medical University", label: "Bangabandhu Sheikh Mujib Medical University" },
    { value: "Bangabandhu Sheikh Mujibur Rahman Agricultural University", label: "Bangabandhu Sheikh Mujibur Rahman Agricultural University" },
    { value: "Hajee Mohammad Danesh Science & Technology University", label: "Hajee Mohammad Danesh Science & Technology University" },
    { value: "Mawlana Bhashani Science and Technology University", label: "Mawlana Bhashani Science and Technology University" },
    { value: "Patuakhali Science and Technology University", label: "Patuakhali Science and Technology University" },
    { value: "Sher-e-Bangla Agricultural University", label: "Sher-e-Bangla Agricultural University" },
    { value: "Dhaka University of Engineering & Technology", label: "Dhaka University of Engineering & Technology" },
    { value: "Rajshahi University of Engineering & Technology", label: "Rajshahi University of Engineering & Technology" },
    { value: "Chittagong University of Engineering & Technology", label: "Chittagong University of Engineering & Technology" },
    { value: "Khulna University of Engineering & Technology", label: "Khulna University of Engineering & Technology" },
    { value: "Jagannath University", label: "Jagannath University" },
    { value: "Jatiya Kabi Kazi Nazrul Islam University", label: "Jatiya Kabi Kazi Nazrul Islam University" },
    { value: "Chittagong Veterinary and Animal Sciences University", label: "Chittagong Veterinary and Animal Sciences University" },
    { value: "Sylhet Agricultural University", label: "Sylhet Agricultural University" },
    { value: "Comilla University", label: "Comilla University" },
    { value: "Noakhali Science and Technology University", label: "Noakhali Science and Technology University" },
    { value: "Jessore University of Science & Technology", label: "Jessore University of Science & Technology" },
    { value: "Pabna University of Science and Technology", label: "Pabna University of Science and Technology" },
    { value: "Bangladesh University of Professionals", label: "Bangladesh University of Professionals" },
    { value: "Begum Rokeya University", label: "Begum Rokeya University" },
    { value: "Bangladesh University of Textiles", label: "Bangladesh University of Textiles" },
    { value: "University of Barisal", label: "University of Barisal" },
    { value: "Bangabandhu Sheikh Mujibur Rahman Science and Technology University", label: "Bangabandhu Sheikh Mujibur Rahman Science and Technology University" },
    { value: "Islamic Arabic University", label: "Islamic Arabic University" },
    { value: "Bangabandhu Sheikh Mujibur Rahman Maritime University", label: "Bangabandhu Sheikh Mujibur Rahman Maritime University" },
    { value: "Rangamati Science and Technology University", label: "Rangamati Science and Technology University" },
    { value: "Dhaka International University", label: "Dhaka International University" },
    { value: "Ahsanullah University of Science and Technology", label: "Ahsanullah University of Science and Technology" },
    { value: "BRAC University", label: "BRAC University" },
    { value: "East West University", label: "East West University" },
    { value: "North South University", label: "North South University" },
    { value: "American International University-Bangladesh", label: "American International University-Bangladesh" },
    { value: "Independent University, Bangladesh", label: "Independent University, Bangladesh" },
    { value: "Bangladesh University of Business and Technology", label: "Bangladesh University of Business and Technology" },
    { value: "Gono Bishwabidyalay", label: "Gono Bishwabidyalay" },
    { value: "Hamdard University Bangladesh", label: "Hamdard University Bangladesh" },
    { value: "International Islamic University, Chittagong", label: "International Islamic University, Chittagong" },
    { value: "Chittagong Independent University (CIU)", label: "Chittagong Independent University (CIU)" },
    { value: "University of Science & Technology Chittagong", label: "University of Science & Technology Chittagong" },
    { value: "Begum Gulchemonara Trust University", label: "Begum Gulchemonara Trust University" },
    { value: "East Delta University", label: "East Delta University" },
    { value: "Bangladesh Army University of Science and Technology", label: "Bangladesh Army University of Science and Technology" },
    { value: "Bangladesh Army International University of Science & Technology", label: "Bangladesh Army International University of Science & Technology" },
    { value: "Britannia University", label: "Britannia University" },
    { value: "Feni University", label: "Feni University" },
    { value: "Bangladesh Army University of Engineering & Technology", label: "Bangladesh Army University of Engineering & Technology" },
    { value: "Premier University, Chittagong", label: "Premier University, Chittagong" },
    { value: "Exim Bank Agricultural University Bangladesh", label: "Exim Bank Agricultural University Bangladesh" },
    { value: "Southern University, Bangladesh", label: "Southern University, Bangladesh" },
    { value: "Port City International University", label: "Port City International University" },
    { value: "Coxs Bazar International University", label: "Coxs Bazar International University" },
    { value: "Notre Dame University Bangladesh", label: "Notre Dame University Bangladesh" },
    { value: "Asian University of Bangladesh", label: "Asian University of Bangladesh" },
    { value: "Asa University Bangladesh", label: "Asa University Bangladesh" },
    { value: "Atish Dipankar University of Science and Technology", label: "Atish Dipankar University of Science and Technology" },
    { value: "Bangladesh Islami University", label: "Bangladesh Islami University" },
    { value: "Bangladesh University", label: "Bangladesh University" },
    { value: "Central Women's University", label: "Central Women's University" },
    { value: "City University, Bangladesh", label: "City University, Bangladesh" },
    { value: "Daffodil International University", label: "Daffodil International University" },
    { value: "Eastern University, Bangladesh", label: "Eastern University, Bangladesh" },
    { value: "Green University of Bangladesh", label: "Green University of Bangladesh" },
    { value: "IBAIS University", label: "IBAIS University" },
    { value: "Sonargaon University", label: "Sonargaon University" },
    { value: "International University of Business Agriculture and Technology", label: "International University of Business Agriculture and Technology" },
    { value: "Manarat International University", label: "Manarat International University" },
    { value: "Millennium University", label: "Millennium University" },
    { value: "Northern University, Bangladesh", label: "Northern University, Bangladesh" },
    { value: "North Western University, Bangladesh", label: "North Western University, Bangladesh" },
    { value: "People's University of Bangladesh", label: "People's University of Bangladesh" },
    { value: "Presidency University", label: "Presidency University" },
    { value: "Pundra University of Science and Technology", label: "Pundra University of Science and Technology" },
    { value: "Prime University", label: "Prime University" },
    { value: "European University of Bangladesh", label: "European University of Bangladesh" },
    { value: "Primeasia University", label: "Primeasia University" },
    { value: "Queens University", label: "Queens University" },
    { value: "Rajshahi Science & Technology University", label: "Rajshahi Science & Technology University" },
    { value: "Royal University of Dhaka", label: "Royal University of Dhaka" },
    { value: "Shanto-Mariam University of Creative Technology", label: "Shanto-Mariam University of Creative Technology" },
    { value: "Southeast University", label: "Southeast University" },
    { value: "Stamford University Bangladesh", label: "Stamford University Bangladesh" },
    { value: "State University of Bangladesh", label: "State University of Bangladesh" },
    { value: "United International University", label: "United International University" },
    { value: "University of Asia Pacific (Bangladesh)", label: "University of Asia Pacific (Bangladesh)" },
    { value: "University of Development Alternative", label: "University of Development Alternative" },
    { value: "University of Information Technology and Sciences", label: "University of Information Technology and Sciences" },
    { value: "University of Liberal Arts Bangladesh", label: "University of Liberal Arts Bangladesh" },
    { value: "Fareast International University", label: "Fareast International University" },
    { value: "University of South Asia, Bangladesh", label: "University of South Asia, Bangladesh" },
    { value: "Uttara University", label: "Uttara University" },
    { value: "Victoria University of Bangladesh", label: "Victoria University of Bangladesh" },
    { value: "Varendra University", label: "Varendra University" },
    { value: "World University of Bangladesh", label: "World University of Bangladesh" },
    { value: "Leading University", label: "Leading University" },
    { value: "Metropolitan University", label: "Metropolitan University" },
    { value: "North East University Bangladesh", label: "North East University Bangladesh" },
    { value: "Sylhet International University", label: "Sylhet International University" },
    { value: "Khwaja Yunus Ali University", label: "Khwaja Yunus Ali University" },
    { value: "Global University Bangladesh", label: "Global University Bangladesh" },
    { value: "University of Creative Technology Chittagong", label: "University of Creative Technology Chittagong" },
    { value: "Z H Sikder University of Science & Technology", label: "Z H Sikder University of Science & Technology" },
    { value: "Central University of Science and Technology", label: "Central University of Science and Technology" },
    { value: "Canadian University of Bangladesh", label: "Canadian University of Bangladesh" },
    { value: "First Capital University of Bangladesh", label: "First Capital University of Bangladesh" },
    { value: "Ishaka International University", label: "Ishaka International University" },
    { value: "Northern University of Business & Technology, Khulna", label: "Northern University of Business & Technology, Khulna" },
    { value: "North Bengal International University", label: "North Bengal International University" },
    { value: "Ranada Prasad Shaha University", label: "Ranada Prasad Shaha University" },
    { value: "Islamic University of Technology", label: "Islamic University of Technology" },
    { value: "Asian University for Women", label: "Asian University for Women" },
    { value: "Bangladesh Open University", label: "Bangladesh Open University" },
    { value: "National University of Bangladesh", label: "National University of Bangladesh" },
    { value: "Islamic Arabic University", label: "Islamic Arabic University" },
];